language: android
dist: trusty
android:
  components:
    - tools
    - build-tools-30.0.2
    - android-30
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

sudo: required

install: true

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease --stacktrace