language: android
dist: trusty
android:
  components:
    - build-tools-30.0.2
    - android-30
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-30
    - sys-img-armeabi-v7a-android-17
before_install:
  - chmod +x gradlew